---
# tasks file for development-environment
- include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
      - "../vars/{{ ansible_distribution }}.yml"
      - "../vars/{{ ansible_os_family }}.yml"
      - "../vars/default.yml"
      skip: true
- name: Packages to Install
  set_fact:
    install_packages:
      - "{{ intellij_ultimate_package_name }}"
      - "{{ neovim_package_name }}"
      - "{{ tmux_package_name }}"
      - "{{ docker_package_name}}"
      - "{{ keychain_package_name }}"
      - "{{ terraform_package_name }}"
- include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "../tasks/{{ ansible_distribution }}-{{ ansible_distribution_major_version | int}}.yml"
        - "../tasks/{{ ansible_distribution }}.yml"
        - "../tasks/{{ ansible_os_family }}.yml"
      skip: true
- name: Install packages
  package:
    name: "{{ install_packages }}"
  # Homebrew should not be run as root
  become: "{{ 'false' if ansible_os_family == 'Darwin' else 'true' }}"
- name: Homebrew install
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - up
    - exa
    - watch
    - wget
